version: 2
build:
  image: latest
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
python:
   version: "3.11"
   install:
     - requirements: docs/requirements.txt
     - method: pip
       path: .
   system_packages: false